// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account/buySpace": {
            "post": {
                "description": "BuySpace",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BuySpace"
                ],
                "summary": "BuySpace",
                "parameters": [
                    {
                        "description": "b",
                        "name": "b",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "type": "string",
                        "description": "size",
                        "name": "size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "BuySpace",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "521": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/logs.APIError"
                        }
                    }
                }
            }
        },
        "/account/buyTraffic": {
            "post": {
                "description": "BuyTraffic",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BuyTraffic"
                ],
                "summary": "BuyTraffic",
                "parameters": [
                    {
                        "description": "b",
                        "name": "b",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "type": "string",
                        "description": "size",
                        "name": "size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "BuyTraffic",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "521": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/logs.APIError"
                        }
                    }
                }
            }
        },
        "/account/getAllowance": {
            "post": {
                "description": "getAllowance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "getAllowance"
                ],
                "summary": "getAllowance",
                "parameters": [
                    {
                        "description": "b",
                        "name": "b",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "type": "string",
                        "description": "type",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "getAllowance",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "521": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/logs.APIError"
                        }
                    }
                }
            }
        },
        "/account/getApproveTsHash": {
            "post": {
                "description": "getApproveTsHash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "getApproveTsHash"
                ],
                "summary": "getApproveTsHash",
                "parameters": [
                    {
                        "description": "b",
                        "name": "b",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "type": "string",
                        "description": "value",
                        "name": "value",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "type",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "getApproveTsHash",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "521": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/logs.APIError"
                        }
                    }
                }
            }
        },
        "/account/getBalance": {
            "post": {
                "description": "get balance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "balance"
                ],
                "summary": "get balance",
                "parameters": [
                    {
                        "description": "b",
                        "name": "b",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "balance",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "521": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/logs.APIError"
                        }
                    }
                }
            }
        },
        "/account/getSpaceHash": {
            "post": {
                "description": "spaceHash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spaceHash"
                ],
                "summary": "spaceHash",
                "parameters": [
                    {
                        "description": "b",
                        "name": "b",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "type": "string",
                        "description": "size",
                        "name": "size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "spaceHash",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "521": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/logs.APIError"
                        }
                    }
                }
            }
        },
        "/account/getSpaceInfo": {
            "post": {
                "description": "getSpaceInfo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "getSpaceInfo"
                ],
                "summary": "getSpaceInfo",
                "parameters": [
                    {
                        "description": "b",
                        "name": "b",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "getSpaceInfo",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "521": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/logs.APIError"
                        }
                    }
                }
            }
        },
        "/account/getSpacePrice/": {
            "get": {
                "description": "get space price",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "price"
                ],
                "summary": "get space price",
                "responses": {
                    "200": {
                        "description": "file id",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "521": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/logs.APIError"
                        }
                    }
                }
            }
        },
        "/account/getTrafficHash": {
            "post": {
                "description": "trafficHash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trafficHash"
                ],
                "summary": "trafficHash",
                "parameters": [
                    {
                        "description": "b",
                        "name": "b",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "type": "string",
                        "description": "size",
                        "name": "size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "trafficHash",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "521": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/logs.APIError"
                        }
                    }
                }
            }
        },
        "/account/getTrafficInfo": {
            "post": {
                "description": "getTrafficInfoHandle",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "getTrafficInfoHandle"
                ],
                "summary": "getTrafficInfoHandle",
                "parameters": [
                    {
                        "description": "b",
                        "name": "b",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "getTrafficInfoHandle",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "521": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/logs.APIError"
                        }
                    }
                }
            }
        },
        "/account/getTrafficPrice/": {
            "get": {
                "description": "get trafficPrice",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "traffic price"
                ],
                "summary": "get trafficPrice",
                "responses": {
                    "200": {
                        "description": "getTrafficPrice",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "521": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/logs.APIError"
                        }
                    }
                }
            }
        },
        "/admin/cashSpace": {
            "get": {
                "description": "cashSpace",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cashSpace"
                ],
                "summary": "cashSpace",
                "parameters": [
                    {
                        "type": "string",
                        "description": "address",
                        "name": "address",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "cashSpace",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "521": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/logs.APIError"
                        }
                    }
                }
            }
        },
        "/ipfs/putOBJ/": {
            "post": {
                "description": "put object",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OBJ"
                ],
                "summary": "put object",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Object file to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "file id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "521": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/logs.APIError"
                        }
                    }
                }
            }
        },
        "/mefs/putOBJ/": {
            "post": {
                "description": "put object",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OBJ"
                ],
                "summary": "put object",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Object file to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "file id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "521": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/logs.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "logs.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "httpstatusCode": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "MiddleWare API",
	Description:      "This is a middleware server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
