// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ipfs/getSpacePrice/": {
            "get": {
                "description": "get space price",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "price"
                ],
                "summary": "get space price",
                "responses": {
                    "200": {
                        "description": "file id",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "521": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/logs.APIError"
                        }
                    }
                }
            }
        },
        "/ipfs/putOBJ/": {
            "post": {
                "description": "put object",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OBJ"
                ],
                "summary": "put object",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Object file to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "file id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "521": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/logs.APIError"
                        }
                    }
                }
            }
        },
        "/mefs/getSpacePrice/": {
            "get": {
                "description": "get space price",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "price"
                ],
                "summary": "get space price",
                "responses": {
                    "200": {
                        "description": "file id",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "521": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/logs.APIError"
                        }
                    }
                }
            }
        },
        "/mefs/putOBJ/": {
            "post": {
                "description": "put object",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OBJ"
                ],
                "summary": "put object",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Object file to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "file id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "521": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/logs.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "logs.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "httpstatusCode": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "MiddleWare API",
	Description:      "This is a middleware server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
